name: salesforce-workflow
on:
  pull_request:
    branches:
    - 'development'
    - 'qa'
    - 'uat'
    - 'master'
    types: 
    - closed  

jobs:
  salesforce:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
  salesforce-deploy:
    needs: salesforce
    if: |
      (github.event_name == 'pull_request'   && github.event.pull_request.merged == true) &&
      ((contains(github.head_ref, 'feature') && github.base_ref == 'development') ||
      (github.head_ref == 'development' && github.base_ref == 'qa') ||
      (github.head_ref == 'qa' && github.base_ref == 'uat') ||
      (github.head_ref == 'uat' && github.base_ref == 'master'))    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    
    - name: Auth sandbox
      env:
        SFDC_POC_USERNAME_DEV: ${{ secrets.SFDC_POCDEV_USERNAME }}
        SFDC_POC_PASSWORD_DEV: ${{ secrets.SFDC_POCDEV_PASSWORD }}
        SFDC_POC_SERVERURL_DEV: ${{ secrets.SFDC_POCDEV_SERVERURL }}
        SFDC_POC_USERNAME_PROD: ${{ secrets.SFDC_POCPROD_USERNAME }}
        SFDC_POC_PASSWORD_PROD: ${{ secrets.SFDC_POCPROD_PASSWORD }}
        SFDC_POC_SERVERURL_PROD: ${{ secrets.SFDC_POCPROD_SERVERURL }}
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "Current branch is $BRANCH"
        if [[ $BRANCH == development ]]; then
          echo $GITHUB_WORKSPACE
          echo $SFDC_POC_PASSWORD_DEV
        elif [[ $BRANCH == master ]]; then
          echo $GITHUB_WORKSPACE
          echo $SFDC_POC_PASSWORD_PROD
        fi
         
        cat /home/runner/work/SalesforcePOC/SalesforcePOC/sample/build.properties
        if [[ $BRANCH == development ]]; then
          sed -i "s/SFDC_POC_PASSWORD/"$SFDC_POC_PASSWORD_DEV"/g" $GITHUB_WORKSPACE/sample/build.properties
          sed -i "s/SFDC_POC_USERNAME/"$SFDC_POC_USERNAME_DEV"/g" $GITHUB_WORKSPACE/sample/build.properties
          sed -i "s/SFDC_POC_SERVERURL/"$SFDC_POC_SERVERURL_DEV"/g" $GITHUB_WORKSPACE/sample/build.properties
        elif [[ $BRANCH == master ]]; then
          sed -i "s/SFDC_POC_PASSWORD/"$SFDC_POC_PASSWORD_PROD"/g" $GITHUB_WORKSPACE/sample/build.properties
          sed -i "s/SFDC_POC_USERNAME/"$SFDC_POC_USERNAME_PROD"/g" $GITHUB_WORKSPACE/sample/build.properties
          sed -i "s/SFDC_POC_SERVERURL/"$SFDC_POC_SERVERURL_PROD"/g" $GITHUB_WORKSPACE/sample/build.properties
        fi
