name: action-jira-linter
on: [pull_request]
jobs:
  jira-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: jira-tools/action-jira-linter@v1.0.1
        name: jira-lint
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          jira-user: ${{ secrets.JIRA_USER }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://mdlzintl.atlassian.net
          skip-comments: true
          validate-issue-status: true
          allowed-issue-statuses: New
          fail-on-error: true
          
