name: Salesforce-workfloW
on:
  pull_request:
    branches:
    - 'development'
    - 'qa'
    - 'uat'
    - 'main'
    types: 
    - closed  

jobs:
  salesforce:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
  salesforce-deploy:
    needs: salesforce
    if: |
      (github.event_name == 'pull_request'   && github.event.pull_request.merged == true) &&
      ((contains(github.head_ref, 'feature') && github.base_ref == 'development') ||
      (github.head_ref == 'qa'  && github.base_ref == 'uat') ||
      (github.head_ref == 'uat'  && github.base_ref == 'main'))   
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        
    
    - name: Auth sandbox
      env:
       SFDC_POC_USERNAME_DEV: ${{ secrets.SFDC_POCDEV_USERNAME }}
       SFDC_POC_PASSWORD_DEV: ${{ secrets.SFDC_POCDEV_PASSWORD }}
       SFDC_POC_SERVERURL_DEV: ${{ secrets.SFDC_POCDEV_SERVERURL }}
       SFDC_POC_USERNAME_PROD: ${{ secrets.SFDC_POCDEV_USERNAME }}
       SFDC_POC_PASSWORD_PROD: ${{ secrets.SFDC_POCDEV_PASSWORD }}
       SFDC_POC_SERVERURL_PROD: ${{ secrets.SFDC_POCDEV_SERVERURL }}  
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        echo "Current branch is $BRANCH"
        if [[ $BRANCH == development ]]; then
          echo $GITHUB_WORKSPACE
        elif [[ $BRANCH == main ]]; then
          echo $GITHUB_WORKSPACE
        fi
         
        cat $GITHUB_WORKSPACE/build.properties
        if [[ $BRANCH == development ]]; then
          sed -i 's|SFDC_POC_USERNAME|'"$SFDC_POC_USERNAME_DEV"'|g' $GITHUB_WORKSPACE/build.properties
          sed -i 's|SFDC_POC_PASSWORD|'"$SFDC_POC_PASSWORD_DEV"'|g' $GITHUB_WORKSPACE/build.properties
          sed -i 's|SFDC_POC_SERVERURL|'"$SFDC_POC_SERVERURL_DEV"'|g' $GITHUB_WORKSPACE/build.properties
        elif [[ $BRANCH == main ]]; then
          sed -i 's|SFDC_POC_USERNAME|'"$SFDC_POC_USERNAME_PROD"'|g' $GITHUB_WORKSPACE/build.properties
          sed -i 's|SFDC_POC_PASSWORD|'"$SFDC_POC_PASSWORD_PROD"'|g' $GITHUB_WORKSPACE/build.properties
          sed -i 's|SFDC_POC_SERVERURL|'"$SFDC_POC_SERVERURL_PROD"'|g' $GITHUB_WORKSPACE/build.properties
        fi
        cat $GITHUB_WORKSPACE/build.properties
        
    - name: Validate build and deploy components into sfdc
      run: |
        ant -version
        export MANIFEST_FOLDER=$(jq -r '.MANIFEST_FOLDER.FOLDER' devops/params.json)
        echo "Manifest folder: $MANIFEST_FOLDER"
        mkdir $GITHUB_WORKSPACE/build/$MANIFEST_FOLDER/lib/  
        cp $GITHUB_WORKSPACE/lib/* $GITHUB_WORKSPACE/build/$MANIFEST_FOLDER/lib/
        cp $GITHUB_WORKSPACE/build/$MANIFEST_FOLDER/lib/ant-salesforce.jar  /usr/share/ant/lib/
        echo "Validation of build file started"
        ant -Dsf.username=sf.username -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dsf.password=sf.password -Dsf.serverurl=sf.serverurl validateRETests -buildfile $GITHUB_WORKSPACE/build/$MANIFEST_FOLDER/build.xml  
              
        if [ $? != 0 ]  
        then
          echo "Validation failed"
        fi  
        echo "Deployment of components started"
        ant deploy $GITHUB_WORKSPACE/build/$MANIFEST_FOLDER/project-manifest-TPM.txt
        if [ $? == 0 ] 
        then
          echo "deployment failed"
        fi
